/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controller.Koneksi;
import Dao.PengetahuanDao;
import Dao.RulesDao;
import Models.tb_model;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormRules extends javax.swing.JFrame {

    Koneksi con;
    Statement st;
    ResultSet res;

    tb_model tbl = new tb_model();
    PengetahuanDao rld = new PengetahuanDao();
    ArrayList listKet = new ArrayList();
    RulesDao rd = new RulesDao();

    private String rs[][];
    String[] namaKolom = {"Id", "Kode Gejala", "Nama Gejala", "Kode Penyebab", "Nama Penyebab"};
    int jmlKolom = namaKolom.length;
    int[] lebar = {100, 100, 600, 100, 600};
    
    private String rs2[][];
    String[] namaKolom2 = {"Kode Rules", "Ket", "Kode Penyebab", "Nama Penyebab"};
    int jmlKolom2 = namaKolom2.length;
    int[] lebar2 = {400, 600, 400, 800};

    public FormRules() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width - getWidth()) / 2;
        int y = (dim.height - getHeight()) / 2;
        setLocation(x, y);
        ShowIdGejala();
        ShowPenyebab();
        Refresh();
    }

    private void ShowPenyebab() {
        con = new Koneksi();
        try {
            st = con.connect().createStatement();
            res = st.executeQuery("SELECT *FROM tb_penyebab");
            while (res.next()) {
                cbKodePenyebab.addItem(res.getString("Id"));
            }
        } catch (SQLException ex) {

        }
    }

    private void Refresh() {
        cbKodePenyebab.setSelectedIndex(0);
        cbKode.setSelectedIndex(0);
        txtNama.setText("");
        rld.setNama_penyebab("");
        btnSave.setEnabled(true);
        btnDelete.setEnabled(false);
        rd.setIdRules(rd.IdRules());
        listKet.isEmpty();
    }

    private void ShowIdGejala() {
        con = new Koneksi();
        try {
            st = con.connect().createStatement();
            res = st.executeQuery("SELECT *FROM tb_gejala");
            while (res.next()) {
                cbKode.addItem(res.getString("kode"));
            }
        } catch (SQLException ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNama = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        cbKode = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbKodePenyebab = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE PENYEBAB", "NAMA PENYEBAB", "KODE GEJALA", "NAMA GEJALA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAMA GEJALA");

        txtNama.setEditable(false);
        txtNama.setColumns(20);
        txtNama.setLineWrap(true);
        txtNama.setRows(5);
        jScrollPane2.setViewportView(txtNama);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KODE GEJALA");

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cbKode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbKode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PILIH" }));
        cbKode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKodeItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KODE PENYEBAB");

        cbKodePenyebab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbKodePenyebab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PILIH" }));
        cbKodePenyebab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKodePenyebabItemStateChanged(evt);
            }
        });
        cbKodePenyebab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKodePenyebabActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSelesai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSelesai.setText("SELESAI");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbKode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbKodePenyebab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbKodePenyebab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnDelete)))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelesai)
                .addContainerGap())
        );

        jTabbedPane1.addTab("FORM UPDATE RULES", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable2KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("SHOW RULES", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:        
        rs2 = rd.Show();
        tbl.SetTabel(jTable2, rs2, namaKolom2, jmlKolom2, lebar2);
    }//GEN-LAST:event_formWindowActivated

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        rld.setIdRules(Integer.parseInt(jTable1.getValueAt(row, 0).toString()));
        cbKode.setSelectedItem(jTable1.getValueAt(row, 1).toString());
        txtNama.setText(jTable1.getValueAt(row, 2).toString());
        cbKodePenyebab.setSelectedItem(jTable1.getValueAt(row, 3).toString());
        rld.setNama_penyebab(jTable1.getValueAt(row, 4).toString());
        btnSave.setEnabled(false);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Konfirmasi", "Apakah Anda Yakin Ingin Menghapus ?", JOptionPane.YES_NO_OPTION);

        if (ok == 0) {
            rld.Delete(rld.getIdRules());
            Refresh();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cbKodePenyebabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKodePenyebabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKodePenyebabActionPerformed

    private void cbKodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKodeItemStateChanged
        // TODO add your handling code here:
        con = new Koneksi();
        try {
            st = con.connect().createStatement();
            res = st.executeQuery("SELECT *FROM tb_gejala WHERE kode = '" + cbKode.getSelectedItem().toString() + "'");
            while (res.next()) {
                txtNama.setText(res.getString("nama"));
            }
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cbKodeItemStateChanged

    private void cbKodePenyebabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKodePenyebabItemStateChanged
        // TODO add your handling code here:
        con = new Koneksi();
        try {
            st = con.connect().createStatement();
            res = st.executeQuery("SELECT *FROM tb_penyebab WHERE Id = '" + cbKodePenyebab.getSelectedItem().toString() + "'");
            while (res.next()) {
                rld.setNama_penyebab(res.getString("nama"));
            }
        } catch (Exception ex) {

        }

        rs = rld.Show(cbKodePenyebab.getSelectedItem().toString());
        tbl.SetTabel(jTable1, rs, namaKolom, jmlKolom, lebar);
    }//GEN-LAST:event_cbKodePenyebabItemStateChanged

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (cbKodePenyebab.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Kode Penyebab");
        } else if (cbKode.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Kode Gejala");
        } else {
            con = new Koneksi();
            try {
                st = con.connect().createStatement();
                res = st.executeQuery("SELECT *FROM tb_pengetahuan WHERE kode_penyebab = '" + cbKodePenyebab.getSelectedItem() + "' AND kode_gejala = '" + cbKode.getSelectedItem() + "'");
                if (res.next()) {
                    JOptionPane.showMessageDialog(null, "Kode Gejala Telah di Tambahkan !!");
                } else {
                    String kodeGejala = cbKode.getSelectedItem().toString();
                    String namaGejala = txtNama.getText().trim();
                    String kodePenyebab = cbKodePenyebab.getSelectedItem().toString();
                    String namaPenyebab = rld.getNama_penyebab();
                    rld.SaveRules(kodeGejala, namaGejala, kodePenyebab, namaPenyebab);
                    Refresh();
                }
            }catch(SQLException ex){
                
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        int rowCount = jTable1.getRowCount();

        for (int a = 0; a < rowCount; a++) {
            listKet.add(jTable1.getValueAt(a, 1).toString() + ", ");
        }

        String ket = "";
        for (int a = 0; a < listKet.size(); a++) {
            ket = ket + listKet.get(a).toString();
        }

        if (cbKodePenyebab.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Kode Terlebih Dahulu");
            cbKodePenyebab.requestFocus();
        } else {
            con = new Koneksi();
            try {
                st = con.connect().createStatement();
                res = st.executeQuery("SELECT *FROM tb_rules WHERE kode_penyebab = '" + cbKodePenyebab.getSelectedItem().toString() + "'");
                if (res.next()) {
                    rd.UpdateRules(cbKodePenyebab.getSelectedItem().toString(), ket);
                    JOptionPane.showMessageDialog(null, "Rules Telah Di Update !!");
                    listKet.clear();

                } else {
                    rd.SaveRules(rd.getIdRules(), ket, cbKodePenyebab.getSelectedItem().toString(), rld.getNama_penyebab());
                    Refresh();
                    listKet.clear();
                }
            } catch (SQLException ex) {

            }
        }
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void jTable2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyChar()== KeyEvent.VK_DELETE){
            int ok = JOptionPane.showConfirmDialog(null, "Apa Anda Ingin Menghapus ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            
            if(ok==0){
                rd.Delete(rd.getIdRules());
                rd.setIdRules("");
            }
        }
        
    }//GEN-LAST:event_jTable2KeyPressed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        
        int row = jTable2.getSelectedRow();
        rd.setIdRules(jTable2.getValueAt(row, 0).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRules().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JComboBox cbKode;
    private javax.swing.JComboBox cbKodePenyebab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea txtNama;
    // End of variables declaration//GEN-END:variables
}
